### ISSUE TITLE
get_inception_score() returns two NaNs

### ISSUE THREAD

**Issue by caradryanl** [w86763777/Pytorch-Unified-Inception-FID-Score#5]
I used a very simple test example to test get_inception_score():
```
    input_image_tensor = torch.zeros([5, 3, 256, 256], dtype=torch.float32)
    IS, IS_std = get_inception_score(input_image_tensor)
```
Both returns, IS and IS_std, was nan with the following trace back:
```
    /ldm/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
        return _methods._mean(a, axis=axis, dtype=dtype,
    /ldm/lib/python3.8/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
        ret = um.true_divide(
    /ldm/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
        ret = ret.dtype.type(ret / rcount)
```
The environments related are listed as follows:
```
    - python=3.8.10
    - cudatoolkit=11.3
    - pytorch=1.10.2
    - torchvision=0.11.3
    - numpy=1.22.3
```
Could you please tell me how to fix this bug?

**Comment by w86763777** [comment]
Since the default `splits` of inception score is `10`. You need at least `10` data to make each split contain at least one data:
```python
import torch
from pytorch_gan_metrics import get_inception_score

input_image_tensor = torch.zeros([10, 3, 256, 256], dtype=torch.float32)
IS, IS_std = get_inception_score(input_image_tensor)
print(IS, IS_std)
```
This gives `1.0 0.0`.

The other option is to reduce the `splits`:
```python
import torch
from pytorch_gan_metrics import get_inception_score

input_image_tensor = torch.zeros([5, 3, 256, 256], dtype=torch.float32)
IS, IS_std = get_inception_score(input_image_tensor, splits=5)
print(IS, IS_std)
```
This also gives `1.0 0.0`.

**Comment by caradryanl** [comment]
> Since the default `splits` of inception score is `10`. You need at least `10` data to make each split contain at least one data:
> 
> ```python
> import torch
> from pytorch_gan_metrics import get_inception_score
> 
> input_image_tensor = torch.zeros([10, 3, 256, 256], dtype=torch.float32)
> IS, IS_std = get_inception_score(input_image_tensor)
> print(IS, IS_std)
> ```
> 
> This gives `1.0 0.0`.
> 
> The other option is to reduce the `splits`:
> 
> ```python
> import torch
> from pytorch_gan_metrics import get_inception_score
> 
> input_image_tensor = torch.zeros([5, 3, 256, 256], dtype=torch.float32)
> IS, IS_std = get_inception_score(input_image_tensor, splits=5)
> print(IS, IS_std)
> ```
> 
> This also gives `1.0 0.0`.

Thank you! This problem is done. I also wonder if it is normal to obtain a non-zero FID between two groups of the s.ame images

**Comment by w86763777** [comment]
> Thank you! This problem is done. I also wonder if it is normal to obtain a non-zero FID between two groups of the s.ame images

Basically impossible, two groups of identical images should have exactly the same feature statistics, so FID will be zero.

**Comment by caradryanl** [comment]
> > Thank you! This problem is done. I also wonder if it is normal to obtain a non-zero FID between two groups of the s.ame images
> 
> Basically impossible, two groups of identical images should have exactly the same feature statistics, so FID will be zero.

I guess it is because I manually transformed the test image into 256x256. When benchmarking images in a size larger than 256x256, what transformation should I conduct on the benchmark images and test images? Should I set the image_size=256 before computing statistics.npz?

**Comment by w86763777** [comment]
> Should I set the image_size=256 before computing statistics.npz?

Exactly right.
You can add `--img_size 256` to the command `python -m pytorch_gan_metrics.calc_fid_stats`, which will resize all images to `256x256` using bilinear interpolation before calculating statistics.

**Comment by caradryanl** [comment]
Thank you! I tried it but still left with a positive FID (around 4). I noticed that there may be some variants when transforming the test images into 256x256. My code is as follows. Is there anything wrong?
```
    img_read = PIL.Image.open(input_path).resize((256, 256), resample=PIL.Image.BICUBIC)
    img = torchvision.transforms.ToTensor(((np.array(img_read) / 255.0).astype(np.float32)))
```

**Comment by w86763777** [comment]
Maybe try `PIL.Image.BILINEAR` instead of `PIL.Image.BICUBIC`.

**Comment by caradryanl** [comment]
> Maybe try `PIL.Image.BILINEAR` instead of `PIL.Image.BICUBIC`.

Thank you! It works. I would close the issue. I think it would be helpful to recommend a BILINEAR transformation in your documentation.

**Comment by w86763777** [comment]
Thanks for your suggestion. I would make some changes in document for that.

A more elegant way to deal with custom image size is resizing images by yourself and save it as a hard copy. The training and statistic calculation should start from this hard copy. This can make the FID comparison more reliable across different works without other details like interpolation method.
