### ISSUE TITLE
FID_WEIGHTS_URL - not found

### ISSUE THREAD

**Issue by pierrelouislemaire** [w86763777/Pytorch-Unified-Inception-FID-Score#7]
Hi,

Github url used in `inception.py`: 

`FID_WEIGHTS_URL = ('https://github.com/w86763777/pytorch_image_generation_metrics/releases/'
                   'download/v0.1.0/pt_inception-2015-12-05-6726825d.pth')` doesn't seem to exist anymore.

When calling `get_inception_score_and_fid()`, I get the following error: HTTPError: HTTP Error 404: Not Found

**Comment by w86763777** [comment]
Thank you for your report. I will fix this in a day.

**Comment by w86763777** [comment]
The URL has been fixed in commit 4245c670745d83d2a22706ad91abfe034e70498e. You can try again in `v0.6.1`. Thanks.
